bcgov/agri-nmp

- Readme.md
> Revert the test change to the Readme

- Server/src/SERVERAPI/Data/static.json
- Server/src/SERVERAPI/Views/Shared/_Layout.cshtml
- Server/src/SERVERAPI/wwwroot/lib/bootstrap/css/custom-main.css
Crop types
Crops
N recommendations
Yields
Crop yields
Crop STP region cd
Crop STK region cd
> Added static data

- Server/src/SERVERAPI/Controllers/NutrientsController.cs
- Server/src/SERVERAPI/ViewModels/ViewModels.cs
- Server/src/SERVERAPI/Views/Nutrients/ManureDetails.cshtml
> manure totals

- COMPLIANCE.yaml
To help with reporting, add a compliance audit file to explictly list the status of PIA and STRA.
- SOAR Assessment Reference Number is 201906250427.
- PIA Assessment Reference Number is PIA#AGRI18008.
> Add missing compliance audit file

- app/Agri.CalculateService/ChemicalBalanceMessage.cs
- app/Agri.Models/Farm/Field.cs
- app/Server/src/SERVERAPI/Pages/Ranch/RanchAnimals/_createEditFormPartial.cshtml
- app/Server/src/SERVERAPI/Pages/Ranch/RanchFeeding/Index.cshtml.cs
- app/Server/src/SERVERAPI/Pages/Ranch/RanchFields/_createEditFormPartial.cshtml
- app/Server/src/SERVERAPI/Pages/Ranch/RanchNutrients/Index.cshtml.cs
- app/Server/src/SERVERAPI/ViewComponents/NavigationViewComponent.cs
Hiding Cancel for entry stage page
> Hide Nutrient page and Feeding pages

- Jenkinsfile
few changes to test the child branch status checks
> post build and deploy status to github

- .pipeline/lib/clean.js
we don't want to delete image streams on cleanup, commented out the "all" delete section
> we don't want to delete image streams on cleanup, commented out the "all" delete section

- .pipeline/lib/clean.js
- OpenShift/dotnet.bc.json
- OpenShift/nmp.bc.json
- OpenShift/nmp.dc.json
- OpenShift/postgresql.dc.json
- OpenShift/redis.bc.json
- OpenShift/redis.dc.json
- OpenShift/weasyprint-bc.json
- OpenShift/weasyprint-dc.json
> stop deleting image streams (#555)

- .pipeline/lib/build.js
- .pipeline/lib/deploy.js
- OpenShift/nmp.dc.json
- OpenShift/postgresql.dc.json
- OpenShift/weasyprint-dc.json
- Readme.md
reduced resource usage on containers, commented out redis, not used currently
> reduced resource usage on containers, commented out redis, not used currently

- app/Agri.Models/Farm/FarmDetails.cs
- app/Server/src/SERVERAPI/Controllers/FarmController.cs
- app/Server/src/SERVERAPI/Models.Impl/UserData.cs
- app/Server/src/SERVERAPI/ViewModels/FarmViewModel.cs
- app/Server/src/SERVERAPI/ViewModels/FarmViewModelBase.cs
- app/Server/src/SERVERAPI/Views/Farm/Farm.cshtml
> Revert "578-add-horticultural-crops-selection-to-farm-information"

- app/Agri.Data/Constants.cs
- app/Agri.Data/SeedData/StaticDataVersion_12.json
- Created a new static data file (staticDataVersion_12) which had new values for default yields for berry crops
> [FEATURE][NMP-627] Created a new static data version that has new default yield values for berries

- app/Agri.Data/Agri.Data.csproj
- x ] The title includes the type of change [`HOTFIX`, `FEATURE`, `etc`]  
- included change to project file which lists embedded resources
> [ADD][NMP-627] add embedded resource reference in project file

- app/Agri.Data/Agri.Data.csproj
- { List all the changes made }
- { Include any screenshots necessary }
> Remove ref to static data version 11.

- app/Agri.Data/AgriConfigurationRepository.cs
- Update the select element dropdown options for:
- "# of plants per acre"
- "Distance between plants, distance between rows"
> [CHANGE][NMP-623] Update plant distance values.

- app/Agri.Data/SeedData/UserPromptsData.json
- app/Server/src/SERVERAPI/Controllers/CropsController.cs
- app/Server/src/SERVERAPI/ViewModels/CropDetailsViewModel.cs
- app/Server/src/SERVERAPI/Views/Crops/CropDetails.cshtml
- app/Server/src/SERVERAPI/wwwroot/css/site.css
- Use the triggerToolTip function (/lib/site.js) to open tooltip on click of "i" icon
- Update User Prompts Data JSON to include the new tooltip string
> [CHANGE][NMP-625] Add is sawdust applied tooltip

- app/Server/src/SERVERAPI/Pages/MiniApps/_miniAppLayout.cshtml
- app/Server/src/SERVERAPI/Views/Shared/_Layout.cshtml
- app/Server/src/SERVERAPI/Views/Shared/_LayoutBare.cshtml
- app/Server/src/SERVERAPI/Views/Shared/_LayoutNoBubbles.cshtml
- app/Server/src/SERVERAPI/Views/Shared/_LayoutNoNav.cshtml
- app/Server/src/SERVERAPI/Views/Shared/_LayoutReport.cshtml
- Updated all instances of GA tag to new GA4 tag. This was done as the old tags were attached to GA properties where the owner of those properties is unknown.
> [CHANGE][NMP-640] Updated google analytics tag to new GA4 tag

- app/Agri.Data/AgriConfigurationRepository.cs
- app/Server/src/SERVERAPI/Views/Crops/CropDetails.cshtml
- { List all the changes made }
- { Include any screenshots necessary }
> [BUG][NMP-624] revert some changes for dynamically update prunings options

- app/Agri.Data/AgriConfigurationRepository.cs
- app/Server/src/SERVERAPI/Views/Crops/CropDetails.cshtml
> Revert "[BUG][NMP-624] revert some changes for dynamically update prunings options"

- app/Agri.Data/AgriConfigurationRepository.cs
- app/Server/src/SERVERAPI/Views/Crops/CropDetails.cshtml
- Reverting the code that is causing this bug
> [BUG][NMP-624] Revert prunings options.

- app/Agri.Data/SeedData/FertigationData.json
In lieu of adding new fertilizers to the existing tables in the database, refactoring of existing code would be necessary. In order to get to an MVP of fertigation quickly, we will utilize this hardcoded data that is structured very similarly to the existing tables.
- added hardcoded data file to support fertigation
> [DATA][NMP-652] added hardcoded data file to support fertigation

- app/Agri.Data/SeedData/FertigationData.json
- app/Agri.Models/Configuration/Fertigation.cs
- app/Agri.Models/Configuration/FertigationType.cs
- app/Agri.Models/Configuration/InjectionRateUnit.cs
- app/Agri.Models/Configuration/ProductRateUnit.cs
- app/Server/src/SERVERAPI/Controllers/NutrientsController.cs
- app/Server/src/SERVERAPI/ViewModels/FertigationDetailsViewModel.cs
- app/Server/src/SERVERAPI/Views/Nutrients/FertigationDetails.cshtml
- app/Server/src/SERVERAPI/Views/Nutrients/FertilizerDetails.cshtml
- Improved spacing and alignment layout in the FertigationDetails view
- Added line spacer to FertilizerDetails view
- Included part 1 of the Fertigation Modal build to be completed in the next upcoming PR
> [FEATURE][NMP-656] Enhanced FertigationDetails Layout and Styling plus Fertigation Modal Build pt 1

- app/Server/src/SERVERAPI/Controllers/NutrientsController.cs
- app/Server/src/SERVERAPI/ViewModels/FertigationDetailsViewModel.cs
- app/Server/src/SERVERAPI/Views/Nutrients/FertigationDetails.cshtml
- Fixed the submit button text not being accurate
- made that button disabled when model not valid
- made datepicker NOT have a minimum date  
- some general cleanup of commented code 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> [TASK][NMP-687] Finalize Liquid Fertigation - btn text, datepicker, cleanup

- app/Server/src/SERVERAPI/Controllers/NutrientsController.cs
- app/Server/src/SERVERAPI/ViewModels/FertigationDetailsViewModel.cs
- app/Server/src/SERVERAPI/Views/Nutrients/FertigationDetails.cshtml
- Added custom liquid fertigation functionality to fertigation model
- included validation for the nutrient fields
> [FEATURE][NMP-682] Custom Liquid Fertigation

- app/Server/src/SERVERAPI/Controllers/NutrientsController.cs
- app/Server/src/SERVERAPI/ViewModels/FertigationDetailsViewModel.cs
- app/Server/src/SERVERAPI/Views/Nutrients/FertigationDetails.cshtml
- All Dry Fertigation fields show up in modal when Dry/Solid Fertigation option is selected
- Validation has been added to fields
> [FEATURE][NMP-664] Build Solid/Dry Fertigation

- app/Agri.Data/SeedData/FertigationData.json
- app/Agri.Models/Configuration/DryFertilizerSolubility.cs
- app/Agri.Models/Configuration/Fertigation.cs
- app/Agri.Models/Configuration/SolubilityUnit.cs
- app/Agri.Models/Farm/NutrientFertilizer.cs
- app/Server/src/SERVERAPI/Attributes/RequiredIfAttribute.cs
- app/Server/src/SERVERAPI/Controllers/NutrientsController.cs
- app/Server/src/SERVERAPI/ViewModels/FertigationDetailsViewModel.cs
- app/Server/src/SERVERAPI/Views/Nutrients/Calculate.cshtml
- app/Server/src/SERVERAPI/Views/Nutrients/FertigationDetails.cshtml
- Added calculations for solid fertigation (custom and regular)
- TODO: Clean up of rounding calculated numbers
- TODO: Conversion of amountToDissolve and TankVolume
- TODO: Investigate edit of dry fertigation (regular)
> [FEAT][NMP-670] Calculations for Solid Fertigation

- app/Server/src/SERVERAPI/Controllers/NutrientsController.cs
- app/Server/src/SERVERAPI/ViewModels/FertigationDetailsViewModel.cs
- app/Server/src/SERVERAPI/Views/Nutrients/FertigationDetails.cshtml
- fixed dry fertigation edit feature
- fixed conversion rates changing calculations
- fixed typos and other small misc
> [REFACTOR][NMP-695]: Cleaned up dry fertigation

- app/Agri.Models/Farm/NutrientFertilizer.cs
- app/Server/src/SERVERAPI/Controllers/NutrientsController.cs
- Small changes to ensure new data from dry fertigation are saved in the edit page
- Resolve issue where edits were not being retained for tank vol, amount to dissolve and solubility
> [FIX][NMP-695] Persist edits to dry fertigation data

- app/Agri.Data/SeedData/FertigationData.json
- app/Server/src/SERVERAPI/Views/Nutrients/FertigationDetails.cshtml
As per ticket changed order of list of fertilizers and layout of nutrient inout boxes on fertigation details modal.
List order changed and nutrient input layout changed.
> Fix[NMP-704]: UI Fertigation List Order and Layout

- app/Server/src/SERVERAPI/Controllers/NutrientsController.cs
- app/Server/src/SERVERAPI/Views/Nutrients/FertigationDetails.cshtml
- app/Server/src/SERVERAPI/appsettings.json
- Changes to tank volume units and amount to dissolve units
- Ensured variables were initialized correctly
- No error message when editing! It works! ![Screenshot 2025-01-09 at 4 19 23 PM](https://github.com/user-attachments/assets/9b2c7f84-bad6-4dfc-9d94-56400d06290a)
> Fix[AGRI-NMP-718]: Bug Unexpected Error Message when Editing Fertigation
